version: '3.4'

services:
  db: 
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password*1"
    ports:
      - 1433:1433
  acmecorpproject.api:
    image: ${DOCKER_REGISTRY-}acmecorpprojectapi
    build:
      context: .
      dockerfile: SampleProject.API\Dockerfile
    depends_on:
            - db
